// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/healthcheck.proto

package comnet.minihadoop.common.message.healthcheck;

public final class Healthcheck {
  private Healthcheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_healthcheck_HealthCheckAsk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_healthcheck_HealthCheckAsk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_healthcheck_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_healthcheck_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/healthcheck.proto\022\013heal" +
      "thcheck\"\034\n\016HealthCheckAsk\022\n\n\002id\030\001 \001(\005\"!\n" +
      "\023HealthCheckResponse\022\n\n\002id\030\001 \001(\005B0\n,comn" +
      "et.minihadoop.common.message.healthcheck" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_healthcheck_HealthCheckAsk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_healthcheck_HealthCheckAsk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_healthcheck_HealthCheckAsk_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_healthcheck_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_healthcheck_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_healthcheck_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
