// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/healthcheck.proto

package comnet.minihadoop.common.message.healthcheck;

public interface HealthCheckAskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:healthcheck.HealthCheckAsk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
