// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/cli.proto

package comnet.minihadoop.common.message.cli;

public final class Cli {
  private Cli() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_CLIMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_CLIMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_HealthCheck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_HealthCheck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_UploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_UploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_UploadReady_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_UploadReady_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cli_ListResponse_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cli_ListResponse_File_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/main/proto/cli.proto\022\003cli\"\214\004\n\nCLIM" +
      "essage\022\"\n\004type\030\001 \001(\0162\024.cli.CLIMessage.Ty" +
      "pe\022\036\n\002hc\030\002 \001(\0132\020.cli.HealthCheckH\000\022)\n\014lo" +
      "ginRequest\030\003 \001(\0132\021.cli.LoginRequestH\000\022+\n" +
      "\rloginResponse\030\004 \001(\0132\022.cli.LoginResponse" +
      "H\000\022+\n\ruploadRequest\030\005 \001(\0132\022.cli.UploadRe" +
      "questH\000\022-\n\016uploadResponse\030\006 \001(\0132\023.cli.Up" +
      "loadResponseH\000\022\'\n\013uploadReady\030\007 \001(\0132\020.cl" +
      "i.UploadReadyH\000\022\'\n\013listRequest\030\010 \001(\0132\020.c" +
      "li.ListRequestH\000\022)\n\014listResponse\030\t \001(\0132\021" +
      ".cli.ListResponseH\000\"\200\001\n\004Type\022\020\n\014HEALTH_C" +
      "HECK\020\000\022\r\n\tLOGIN_REQ\020\001\022\r\n\tLOGIN_RES\020\002\022\016\n\n" +
      "UPLOAD_REQ\020\003\022\016\n\nUPLOAD_RES\020\004\022\020\n\014UPLOAD_R" +
      "EADY\020\005\022\n\n\006LS_REQ\020\006\022\n\n\006LS_RES\020\007B\006\n\004data\"," +
      "\n\014LoginRequest\022\n\n\002ID\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\014\"{\n\rLoginResponse\022\017\n\007success\030\001 \001(\010\022&" +
      "\n\005error\030\002 \001(\0162\027.cli.LoginResponse.Type\"1" +
      "\n\004Type\022\013\n\007SUCCESS\020\000\022\014\n\010WRONG_PW\020\001\022\016\n\nINV" +
      "ALID_ID\020\002\"\036\n\013HealthCheck\022\017\n\007success\030\001 \001(" +
      "\010\"3\n\rUploadRequest\022\020\n\010filename\030\001 \001(\t\022\020\n\010" +
      "filesize\030\002 \001(\003\"\203\001\n\016UploadResponse\022(\n\006sta" +
      "tus\030\001 \001(\0162\030.cli.UploadResponse.Type\022\020\n\010h" +
      "ostname\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"\'\n\004Type\022\013\n\007S" +
      "UCCESS\020\000\022\022\n\016INTERNAL_ERROR\020\001\"-\n\013UploadRe" +
      "ady\022\020\n\010hostname\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"\033\n\013L" +
      "istRequest\022\014\n\004path\030\001 \001(\t\"a\n\014ListResponse" +
      "\022%\n\005files\030\001 \003(\0132\026.cli.ListResponse.File\032" +
      "*\n\004File\022\020\n\010filename\030\001 \001(\t\022\020\n\010filesize\030\002 " +
      "\001(\003B(\n$comnet.minihadoop.common.message." +
      "cliP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cli_CLIMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cli_CLIMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_CLIMessage_descriptor,
        new java.lang.String[] { "Type", "Hc", "LoginRequest", "LoginResponse", "UploadRequest", "UploadResponse", "UploadReady", "ListRequest", "ListResponse", "Data", });
    internal_static_cli_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cli_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_LoginRequest_descriptor,
        new java.lang.String[] { "ID", "Password", });
    internal_static_cli_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cli_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_LoginResponse_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_cli_HealthCheck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cli_HealthCheck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_HealthCheck_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_cli_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cli_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_UploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Filesize", });
    internal_static_cli_UploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cli_UploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_UploadResponse_descriptor,
        new java.lang.String[] { "Status", "Hostname", "Port", });
    internal_static_cli_UploadReady_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cli_UploadReady_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_UploadReady_descriptor,
        new java.lang.String[] { "Hostname", "Port", });
    internal_static_cli_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cli_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_ListRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_cli_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cli_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_ListResponse_descriptor,
        new java.lang.String[] { "Files", });
    internal_static_cli_ListResponse_File_descriptor =
      internal_static_cli_ListResponse_descriptor.getNestedTypes().get(0);
    internal_static_cli_ListResponse_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cli_ListResponse_File_descriptor,
        new java.lang.String[] { "Filename", "Filesize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
