// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/cli.proto

package comnet.minihadoop.common.message.cli;

/**
 * Protobuf type {@code cli.CLIMessage}
 */
public  final class CLIMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cli.CLIMessage)
    CLIMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CLIMessage.newBuilder() to construct.
  private CLIMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CLIMessage() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CLIMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CLIMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            comnet.minihadoop.common.message.cli.HealthCheck.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((comnet.minihadoop.common.message.cli.HealthCheck) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.HealthCheck.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.HealthCheck) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            comnet.minihadoop.common.message.cli.LoginRequest.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((comnet.minihadoop.common.message.cli.LoginRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.LoginRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.LoginRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          case 34: {
            comnet.minihadoop.common.message.cli.LoginResponse.Builder subBuilder = null;
            if (dataCase_ == 4) {
              subBuilder = ((comnet.minihadoop.common.message.cli.LoginResponse) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.LoginResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.LoginResponse) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 4;
            break;
          }
          case 42: {
            comnet.minihadoop.common.message.cli.UploadRequest.Builder subBuilder = null;
            if (dataCase_ == 5) {
              subBuilder = ((comnet.minihadoop.common.message.cli.UploadRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.UploadRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 5;
            break;
          }
          case 50: {
            comnet.minihadoop.common.message.cli.UploadResponse.Builder subBuilder = null;
            if (dataCase_ == 6) {
              subBuilder = ((comnet.minihadoop.common.message.cli.UploadResponse) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.UploadResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.UploadResponse) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 6;
            break;
          }
          case 58: {
            comnet.minihadoop.common.message.cli.UploadReady.Builder subBuilder = null;
            if (dataCase_ == 7) {
              subBuilder = ((comnet.minihadoop.common.message.cli.UploadReady) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.UploadReady.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.UploadReady) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 7;
            break;
          }
          case 66: {
            comnet.minihadoop.common.message.cli.ListRequest.Builder subBuilder = null;
            if (dataCase_ == 8) {
              subBuilder = ((comnet.minihadoop.common.message.cli.ListRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.ListRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.ListRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 8;
            break;
          }
          case 74: {
            comnet.minihadoop.common.message.cli.ListResponse.Builder subBuilder = null;
            if (dataCase_ == 9) {
              subBuilder = ((comnet.minihadoop.common.message.cli.ListResponse) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.cli.ListResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.cli.ListResponse) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 9;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return comnet.minihadoop.common.message.cli.Cli.internal_static_cli_CLIMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return comnet.minihadoop.common.message.cli.Cli.internal_static_cli_CLIMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            comnet.minihadoop.common.message.cli.CLIMessage.class, comnet.minihadoop.common.message.cli.CLIMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code cli.CLIMessage.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEALTH_CHECK = 0;</code>
     */
    HEALTH_CHECK(0),
    /**
     * <code>LOGIN_REQ = 1;</code>
     */
    LOGIN_REQ(1),
    /**
     * <code>LOGIN_RES = 2;</code>
     */
    LOGIN_RES(2),
    /**
     * <code>UPLOAD_REQ = 3;</code>
     */
    UPLOAD_REQ(3),
    /**
     * <code>UPLOAD_RES = 4;</code>
     */
    UPLOAD_RES(4),
    /**
     * <code>UPLOAD_READY = 5;</code>
     */
    UPLOAD_READY(5),
    /**
     * <code>LS_REQ = 6;</code>
     */
    LS_REQ(6),
    /**
     * <code>LS_RES = 7;</code>
     */
    LS_RES(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HEALTH_CHECK = 0;</code>
     */
    public static final int HEALTH_CHECK_VALUE = 0;
    /**
     * <code>LOGIN_REQ = 1;</code>
     */
    public static final int LOGIN_REQ_VALUE = 1;
    /**
     * <code>LOGIN_RES = 2;</code>
     */
    public static final int LOGIN_RES_VALUE = 2;
    /**
     * <code>UPLOAD_REQ = 3;</code>
     */
    public static final int UPLOAD_REQ_VALUE = 3;
    /**
     * <code>UPLOAD_RES = 4;</code>
     */
    public static final int UPLOAD_RES_VALUE = 4;
    /**
     * <code>UPLOAD_READY = 5;</code>
     */
    public static final int UPLOAD_READY_VALUE = 5;
    /**
     * <code>LS_REQ = 6;</code>
     */
    public static final int LS_REQ_VALUE = 6;
    /**
     * <code>LS_RES = 7;</code>
     */
    public static final int LS_RES_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return HEALTH_CHECK;
        case 1: return LOGIN_REQ;
        case 2: return LOGIN_RES;
        case 3: return UPLOAD_REQ;
        case 4: return UPLOAD_RES;
        case 5: return UPLOAD_READY;
        case 6: return LS_REQ;
        case 7: return LS_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.cli.CLIMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cli.CLIMessage.Type)
  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HC(2),
    LOGINREQUEST(3),
    LOGINRESPONSE(4),
    UPLOADREQUEST(5),
    UPLOADRESPONSE(6),
    UPLOADREADY(7),
    LISTREQUEST(8),
    LISTRESPONSE(9),
    DATA_NOT_SET(0);
    private final int value;
    DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return HC;
        case 3: return LOGINREQUEST;
        case 4: return LOGINRESPONSE;
        case 5: return UPLOADREQUEST;
        case 6: return UPLOADRESPONSE;
        case 7: return UPLOADREADY;
        case 8: return LISTREQUEST;
        case 9: return LISTRESPONSE;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  }

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.cli.CLIMessage.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.cli.CLIMessage.Type type = 1;</code>
   * @return The type.
   */
  public comnet.minihadoop.common.message.cli.CLIMessage.Type getType() {
    @SuppressWarnings("deprecation")
    comnet.minihadoop.common.message.cli.CLIMessage.Type result = comnet.minihadoop.common.message.cli.CLIMessage.Type.valueOf(type_);
    return result == null ? comnet.minihadoop.common.message.cli.CLIMessage.Type.UNRECOGNIZED : result;
  }

  public static final int HC_FIELD_NUMBER = 2;
  /**
   * <code>.cli.HealthCheck hc = 2;</code>
   * @return Whether the hc field is set.
   */
  public boolean hasHc() {
    return dataCase_ == 2;
  }
  /**
   * <code>.cli.HealthCheck hc = 2;</code>
   * @return The hc.
   */
  public comnet.minihadoop.common.message.cli.HealthCheck getHc() {
    if (dataCase_ == 2) {
       return (comnet.minihadoop.common.message.cli.HealthCheck) data_;
    }
    return comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
  }
  /**
   * <code>.cli.HealthCheck hc = 2;</code>
   */
  public comnet.minihadoop.common.message.cli.HealthCheckOrBuilder getHcOrBuilder() {
    if (dataCase_ == 2) {
       return (comnet.minihadoop.common.message.cli.HealthCheck) data_;
    }
    return comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
  }

  public static final int LOGINREQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.cli.LoginRequest loginRequest = 3;</code>
   * @return Whether the loginRequest field is set.
   */
  public boolean hasLoginRequest() {
    return dataCase_ == 3;
  }
  /**
   * <code>.cli.LoginRequest loginRequest = 3;</code>
   * @return The loginRequest.
   */
  public comnet.minihadoop.common.message.cli.LoginRequest getLoginRequest() {
    if (dataCase_ == 3) {
       return (comnet.minihadoop.common.message.cli.LoginRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
  }
  /**
   * <code>.cli.LoginRequest loginRequest = 3;</code>
   */
  public comnet.minihadoop.common.message.cli.LoginRequestOrBuilder getLoginRequestOrBuilder() {
    if (dataCase_ == 3) {
       return (comnet.minihadoop.common.message.cli.LoginRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
  }

  public static final int LOGINRESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.cli.LoginResponse loginResponse = 4;</code>
   * @return Whether the loginResponse field is set.
   */
  public boolean hasLoginResponse() {
    return dataCase_ == 4;
  }
  /**
   * <code>.cli.LoginResponse loginResponse = 4;</code>
   * @return The loginResponse.
   */
  public comnet.minihadoop.common.message.cli.LoginResponse getLoginResponse() {
    if (dataCase_ == 4) {
       return (comnet.minihadoop.common.message.cli.LoginResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
  }
  /**
   * <code>.cli.LoginResponse loginResponse = 4;</code>
   */
  public comnet.minihadoop.common.message.cli.LoginResponseOrBuilder getLoginResponseOrBuilder() {
    if (dataCase_ == 4) {
       return (comnet.minihadoop.common.message.cli.LoginResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
  }

  public static final int UPLOADREQUEST_FIELD_NUMBER = 5;
  /**
   * <code>.cli.UploadRequest uploadRequest = 5;</code>
   * @return Whether the uploadRequest field is set.
   */
  public boolean hasUploadRequest() {
    return dataCase_ == 5;
  }
  /**
   * <code>.cli.UploadRequest uploadRequest = 5;</code>
   * @return The uploadRequest.
   */
  public comnet.minihadoop.common.message.cli.UploadRequest getUploadRequest() {
    if (dataCase_ == 5) {
       return (comnet.minihadoop.common.message.cli.UploadRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
  }
  /**
   * <code>.cli.UploadRequest uploadRequest = 5;</code>
   */
  public comnet.minihadoop.common.message.cli.UploadRequestOrBuilder getUploadRequestOrBuilder() {
    if (dataCase_ == 5) {
       return (comnet.minihadoop.common.message.cli.UploadRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
  }

  public static final int UPLOADRESPONSE_FIELD_NUMBER = 6;
  /**
   * <code>.cli.UploadResponse uploadResponse = 6;</code>
   * @return Whether the uploadResponse field is set.
   */
  public boolean hasUploadResponse() {
    return dataCase_ == 6;
  }
  /**
   * <code>.cli.UploadResponse uploadResponse = 6;</code>
   * @return The uploadResponse.
   */
  public comnet.minihadoop.common.message.cli.UploadResponse getUploadResponse() {
    if (dataCase_ == 6) {
       return (comnet.minihadoop.common.message.cli.UploadResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
  }
  /**
   * <code>.cli.UploadResponse uploadResponse = 6;</code>
   */
  public comnet.minihadoop.common.message.cli.UploadResponseOrBuilder getUploadResponseOrBuilder() {
    if (dataCase_ == 6) {
       return (comnet.minihadoop.common.message.cli.UploadResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
  }

  public static final int UPLOADREADY_FIELD_NUMBER = 7;
  /**
   * <code>.cli.UploadReady uploadReady = 7;</code>
   * @return Whether the uploadReady field is set.
   */
  public boolean hasUploadReady() {
    return dataCase_ == 7;
  }
  /**
   * <code>.cli.UploadReady uploadReady = 7;</code>
   * @return The uploadReady.
   */
  public comnet.minihadoop.common.message.cli.UploadReady getUploadReady() {
    if (dataCase_ == 7) {
       return (comnet.minihadoop.common.message.cli.UploadReady) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
  }
  /**
   * <code>.cli.UploadReady uploadReady = 7;</code>
   */
  public comnet.minihadoop.common.message.cli.UploadReadyOrBuilder getUploadReadyOrBuilder() {
    if (dataCase_ == 7) {
       return (comnet.minihadoop.common.message.cli.UploadReady) data_;
    }
    return comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
  }

  public static final int LISTREQUEST_FIELD_NUMBER = 8;
  /**
   * <code>.cli.ListRequest listRequest = 8;</code>
   * @return Whether the listRequest field is set.
   */
  public boolean hasListRequest() {
    return dataCase_ == 8;
  }
  /**
   * <code>.cli.ListRequest listRequest = 8;</code>
   * @return The listRequest.
   */
  public comnet.minihadoop.common.message.cli.ListRequest getListRequest() {
    if (dataCase_ == 8) {
       return (comnet.minihadoop.common.message.cli.ListRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
  }
  /**
   * <code>.cli.ListRequest listRequest = 8;</code>
   */
  public comnet.minihadoop.common.message.cli.ListRequestOrBuilder getListRequestOrBuilder() {
    if (dataCase_ == 8) {
       return (comnet.minihadoop.common.message.cli.ListRequest) data_;
    }
    return comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
  }

  public static final int LISTRESPONSE_FIELD_NUMBER = 9;
  /**
   * <code>.cli.ListResponse listResponse = 9;</code>
   * @return Whether the listResponse field is set.
   */
  public boolean hasListResponse() {
    return dataCase_ == 9;
  }
  /**
   * <code>.cli.ListResponse listResponse = 9;</code>
   * @return The listResponse.
   */
  public comnet.minihadoop.common.message.cli.ListResponse getListResponse() {
    if (dataCase_ == 9) {
       return (comnet.minihadoop.common.message.cli.ListResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
  }
  /**
   * <code>.cli.ListResponse listResponse = 9;</code>
   */
  public comnet.minihadoop.common.message.cli.ListResponseOrBuilder getListResponseOrBuilder() {
    if (dataCase_ == 9) {
       return (comnet.minihadoop.common.message.cli.ListResponse) data_;
    }
    return comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != comnet.minihadoop.common.message.cli.CLIMessage.Type.HEALTH_CHECK.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (comnet.minihadoop.common.message.cli.HealthCheck) data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (comnet.minihadoop.common.message.cli.LoginRequest) data_);
    }
    if (dataCase_ == 4) {
      output.writeMessage(4, (comnet.minihadoop.common.message.cli.LoginResponse) data_);
    }
    if (dataCase_ == 5) {
      output.writeMessage(5, (comnet.minihadoop.common.message.cli.UploadRequest) data_);
    }
    if (dataCase_ == 6) {
      output.writeMessage(6, (comnet.minihadoop.common.message.cli.UploadResponse) data_);
    }
    if (dataCase_ == 7) {
      output.writeMessage(7, (comnet.minihadoop.common.message.cli.UploadReady) data_);
    }
    if (dataCase_ == 8) {
      output.writeMessage(8, (comnet.minihadoop.common.message.cli.ListRequest) data_);
    }
    if (dataCase_ == 9) {
      output.writeMessage(9, (comnet.minihadoop.common.message.cli.ListResponse) data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != comnet.minihadoop.common.message.cli.CLIMessage.Type.HEALTH_CHECK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (comnet.minihadoop.common.message.cli.HealthCheck) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (comnet.minihadoop.common.message.cli.LoginRequest) data_);
    }
    if (dataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (comnet.minihadoop.common.message.cli.LoginResponse) data_);
    }
    if (dataCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (comnet.minihadoop.common.message.cli.UploadRequest) data_);
    }
    if (dataCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (comnet.minihadoop.common.message.cli.UploadResponse) data_);
    }
    if (dataCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (comnet.minihadoop.common.message.cli.UploadReady) data_);
    }
    if (dataCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (comnet.minihadoop.common.message.cli.ListRequest) data_);
    }
    if (dataCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (comnet.minihadoop.common.message.cli.ListResponse) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof comnet.minihadoop.common.message.cli.CLIMessage)) {
      return super.equals(obj);
    }
    comnet.minihadoop.common.message.cli.CLIMessage other = (comnet.minihadoop.common.message.cli.CLIMessage) obj;

    if (type_ != other.type_) return false;
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getHc()
            .equals(other.getHc())) return false;
        break;
      case 3:
        if (!getLoginRequest()
            .equals(other.getLoginRequest())) return false;
        break;
      case 4:
        if (!getLoginResponse()
            .equals(other.getLoginResponse())) return false;
        break;
      case 5:
        if (!getUploadRequest()
            .equals(other.getUploadRequest())) return false;
        break;
      case 6:
        if (!getUploadResponse()
            .equals(other.getUploadResponse())) return false;
        break;
      case 7:
        if (!getUploadReady()
            .equals(other.getUploadReady())) return false;
        break;
      case 8:
        if (!getListRequest()
            .equals(other.getListRequest())) return false;
        break;
      case 9:
        if (!getListResponse()
            .equals(other.getListResponse())) return false;
        break;
      case 0:
      default:
    }
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + HC_FIELD_NUMBER;
        hash = (53 * hash) + getHc().hashCode();
        break;
      case 3:
        hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + UPLOADREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUploadRequest().hashCode();
        break;
      case 6:
        hash = (37 * hash) + UPLOADRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUploadResponse().hashCode();
        break;
      case 7:
        hash = (37 * hash) + UPLOADREADY_FIELD_NUMBER;
        hash = (53 * hash) + getUploadReady().hashCode();
        break;
      case 8:
        hash = (37 * hash) + LISTREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getListRequest().hashCode();
        break;
      case 9:
        hash = (37 * hash) + LISTRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getListResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.cli.CLIMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(comnet.minihadoop.common.message.cli.CLIMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cli.CLIMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cli.CLIMessage)
      comnet.minihadoop.common.message.cli.CLIMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.cli.Cli.internal_static_cli_CLIMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comnet.minihadoop.common.message.cli.Cli.internal_static_cli_CLIMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comnet.minihadoop.common.message.cli.CLIMessage.class, comnet.minihadoop.common.message.cli.CLIMessage.Builder.class);
    }

    // Construct using comnet.minihadoop.common.message.cli.CLIMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return comnet.minihadoop.common.message.cli.Cli.internal_static_cli_CLIMessage_descriptor;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.cli.CLIMessage getDefaultInstanceForType() {
      return comnet.minihadoop.common.message.cli.CLIMessage.getDefaultInstance();
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.cli.CLIMessage build() {
      comnet.minihadoop.common.message.cli.CLIMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.cli.CLIMessage buildPartial() {
      comnet.minihadoop.common.message.cli.CLIMessage result = new comnet.minihadoop.common.message.cli.CLIMessage(this);
      result.type_ = type_;
      if (dataCase_ == 2) {
        if (hcBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = hcBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        if (loginRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = loginRequestBuilder_.build();
        }
      }
      if (dataCase_ == 4) {
        if (loginResponseBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = loginResponseBuilder_.build();
        }
      }
      if (dataCase_ == 5) {
        if (uploadRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = uploadRequestBuilder_.build();
        }
      }
      if (dataCase_ == 6) {
        if (uploadResponseBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = uploadResponseBuilder_.build();
        }
      }
      if (dataCase_ == 7) {
        if (uploadReadyBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = uploadReadyBuilder_.build();
        }
      }
      if (dataCase_ == 8) {
        if (listRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = listRequestBuilder_.build();
        }
      }
      if (dataCase_ == 9) {
        if (listResponseBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = listResponseBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof comnet.minihadoop.common.message.cli.CLIMessage) {
        return mergeFrom((comnet.minihadoop.common.message.cli.CLIMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(comnet.minihadoop.common.message.cli.CLIMessage other) {
      if (other == comnet.minihadoop.common.message.cli.CLIMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getDataCase()) {
        case HC: {
          mergeHc(other.getHc());
          break;
        }
        case LOGINREQUEST: {
          mergeLoginRequest(other.getLoginRequest());
          break;
        }
        case LOGINRESPONSE: {
          mergeLoginResponse(other.getLoginResponse());
          break;
        }
        case UPLOADREQUEST: {
          mergeUploadRequest(other.getUploadRequest());
          break;
        }
        case UPLOADRESPONSE: {
          mergeUploadResponse(other.getUploadResponse());
          break;
        }
        case UPLOADREADY: {
          mergeUploadReady(other.getUploadReady());
          break;
        }
        case LISTREQUEST: {
          mergeListRequest(other.getListRequest());
          break;
        }
        case LISTRESPONSE: {
          mergeListResponse(other.getListResponse());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      comnet.minihadoop.common.message.cli.CLIMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (comnet.minihadoop.common.message.cli.CLIMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.cli.CLIMessage.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.cli.CLIMessage.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.cli.CLIMessage.Type type = 1;</code>
     * @return The type.
     */
    public comnet.minihadoop.common.message.cli.CLIMessage.Type getType() {
      @SuppressWarnings("deprecation")
      comnet.minihadoop.common.message.cli.CLIMessage.Type result = comnet.minihadoop.common.message.cli.CLIMessage.Type.valueOf(type_);
      return result == null ? comnet.minihadoop.common.message.cli.CLIMessage.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.cli.CLIMessage.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(comnet.minihadoop.common.message.cli.CLIMessage.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cli.CLIMessage.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.HealthCheck, comnet.minihadoop.common.message.cli.HealthCheck.Builder, comnet.minihadoop.common.message.cli.HealthCheckOrBuilder> hcBuilder_;
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     * @return Whether the hc field is set.
     */
    public boolean hasHc() {
      return dataCase_ == 2;
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     * @return The hc.
     */
    public comnet.minihadoop.common.message.cli.HealthCheck getHc() {
      if (hcBuilder_ == null) {
        if (dataCase_ == 2) {
          return (comnet.minihadoop.common.message.cli.HealthCheck) data_;
        }
        return comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return hcBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public Builder setHc(comnet.minihadoop.common.message.cli.HealthCheck value) {
      if (hcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        hcBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public Builder setHc(
        comnet.minihadoop.common.message.cli.HealthCheck.Builder builderForValue) {
      if (hcBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        hcBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public Builder mergeHc(comnet.minihadoop.common.message.cli.HealthCheck value) {
      if (hcBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.HealthCheck.newBuilder((comnet.minihadoop.common.message.cli.HealthCheck) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          hcBuilder_.mergeFrom(value);
        }
        hcBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public Builder clearHc() {
      if (hcBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        hcBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public comnet.minihadoop.common.message.cli.HealthCheck.Builder getHcBuilder() {
      return getHcFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    public comnet.minihadoop.common.message.cli.HealthCheckOrBuilder getHcOrBuilder() {
      if ((dataCase_ == 2) && (hcBuilder_ != null)) {
        return hcBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (comnet.minihadoop.common.message.cli.HealthCheck) data_;
        }
        return comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.HealthCheck hc = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.HealthCheck, comnet.minihadoop.common.message.cli.HealthCheck.Builder, comnet.minihadoop.common.message.cli.HealthCheckOrBuilder> 
        getHcFieldBuilder() {
      if (hcBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = comnet.minihadoop.common.message.cli.HealthCheck.getDefaultInstance();
        }
        hcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.HealthCheck, comnet.minihadoop.common.message.cli.HealthCheck.Builder, comnet.minihadoop.common.message.cli.HealthCheckOrBuilder>(
                (comnet.minihadoop.common.message.cli.HealthCheck) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();
      return hcBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.LoginRequest, comnet.minihadoop.common.message.cli.LoginRequest.Builder, comnet.minihadoop.common.message.cli.LoginRequestOrBuilder> loginRequestBuilder_;
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     * @return Whether the loginRequest field is set.
     */
    public boolean hasLoginRequest() {
      return dataCase_ == 3;
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     * @return The loginRequest.
     */
    public comnet.minihadoop.common.message.cli.LoginRequest getLoginRequest() {
      if (loginRequestBuilder_ == null) {
        if (dataCase_ == 3) {
          return (comnet.minihadoop.common.message.cli.LoginRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return loginRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public Builder setLoginRequest(comnet.minihadoop.common.message.cli.LoginRequest value) {
      if (loginRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        loginRequestBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public Builder setLoginRequest(
        comnet.minihadoop.common.message.cli.LoginRequest.Builder builderForValue) {
      if (loginRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        loginRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public Builder mergeLoginRequest(comnet.minihadoop.common.message.cli.LoginRequest value) {
      if (loginRequestBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.LoginRequest.newBuilder((comnet.minihadoop.common.message.cli.LoginRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          loginRequestBuilder_.mergeFrom(value);
        }
        loginRequestBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public Builder clearLoginRequest() {
      if (loginRequestBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        loginRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public comnet.minihadoop.common.message.cli.LoginRequest.Builder getLoginRequestBuilder() {
      return getLoginRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    public comnet.minihadoop.common.message.cli.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      if ((dataCase_ == 3) && (loginRequestBuilder_ != null)) {
        return loginRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (comnet.minihadoop.common.message.cli.LoginRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.LoginRequest loginRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.LoginRequest, comnet.minihadoop.common.message.cli.LoginRequest.Builder, comnet.minihadoop.common.message.cli.LoginRequestOrBuilder> 
        getLoginRequestFieldBuilder() {
      if (loginRequestBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = comnet.minihadoop.common.message.cli.LoginRequest.getDefaultInstance();
        }
        loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.LoginRequest, comnet.minihadoop.common.message.cli.LoginRequest.Builder, comnet.minihadoop.common.message.cli.LoginRequestOrBuilder>(
                (comnet.minihadoop.common.message.cli.LoginRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();
      return loginRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.LoginResponse, comnet.minihadoop.common.message.cli.LoginResponse.Builder, comnet.minihadoop.common.message.cli.LoginResponseOrBuilder> loginResponseBuilder_;
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     * @return Whether the loginResponse field is set.
     */
    public boolean hasLoginResponse() {
      return dataCase_ == 4;
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     * @return The loginResponse.
     */
    public comnet.minihadoop.common.message.cli.LoginResponse getLoginResponse() {
      if (loginResponseBuilder_ == null) {
        if (dataCase_ == 4) {
          return (comnet.minihadoop.common.message.cli.LoginResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
      } else {
        if (dataCase_ == 4) {
          return loginResponseBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public Builder setLoginResponse(comnet.minihadoop.common.message.cli.LoginResponse value) {
      if (loginResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        loginResponseBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public Builder setLoginResponse(
        comnet.minihadoop.common.message.cli.LoginResponse.Builder builderForValue) {
      if (loginResponseBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        loginResponseBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public Builder mergeLoginResponse(comnet.minihadoop.common.message.cli.LoginResponse value) {
      if (loginResponseBuilder_ == null) {
        if (dataCase_ == 4 &&
            data_ != comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.LoginResponse.newBuilder((comnet.minihadoop.common.message.cli.LoginResponse) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 4) {
          loginResponseBuilder_.mergeFrom(value);
        }
        loginResponseBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public Builder clearLoginResponse() {
      if (loginResponseBuilder_ == null) {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
        }
        loginResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public comnet.minihadoop.common.message.cli.LoginResponse.Builder getLoginResponseBuilder() {
      return getLoginResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    public comnet.minihadoop.common.message.cli.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      if ((dataCase_ == 4) && (loginResponseBuilder_ != null)) {
        return loginResponseBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 4) {
          return (comnet.minihadoop.common.message.cli.LoginResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.LoginResponse loginResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.LoginResponse, comnet.minihadoop.common.message.cli.LoginResponse.Builder, comnet.minihadoop.common.message.cli.LoginResponseOrBuilder> 
        getLoginResponseFieldBuilder() {
      if (loginResponseBuilder_ == null) {
        if (!(dataCase_ == 4)) {
          data_ = comnet.minihadoop.common.message.cli.LoginResponse.getDefaultInstance();
        }
        loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.LoginResponse, comnet.minihadoop.common.message.cli.LoginResponse.Builder, comnet.minihadoop.common.message.cli.LoginResponseOrBuilder>(
                (comnet.minihadoop.common.message.cli.LoginResponse) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 4;
      onChanged();
      return loginResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadRequest, comnet.minihadoop.common.message.cli.UploadRequest.Builder, comnet.minihadoop.common.message.cli.UploadRequestOrBuilder> uploadRequestBuilder_;
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     * @return Whether the uploadRequest field is set.
     */
    public boolean hasUploadRequest() {
      return dataCase_ == 5;
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     * @return The uploadRequest.
     */
    public comnet.minihadoop.common.message.cli.UploadRequest getUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 5) {
          return (comnet.minihadoop.common.message.cli.UploadRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 5) {
          return uploadRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public Builder setUploadRequest(comnet.minihadoop.common.message.cli.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public Builder setUploadRequest(
        comnet.minihadoop.common.message.cli.UploadRequest.Builder builderForValue) {
      if (uploadRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public Builder mergeUploadRequest(comnet.minihadoop.common.message.cli.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 5 &&
            data_ != comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.UploadRequest.newBuilder((comnet.minihadoop.common.message.cli.UploadRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 5) {
          uploadRequestBuilder_.mergeFrom(value);
        }
        uploadRequestBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public Builder clearUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
        }
        uploadRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadRequest.Builder getUploadRequestBuilder() {
      return getUploadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadRequestOrBuilder getUploadRequestOrBuilder() {
      if ((dataCase_ == 5) && (uploadRequestBuilder_ != null)) {
        return uploadRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 5) {
          return (comnet.minihadoop.common.message.cli.UploadRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadRequest uploadRequest = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadRequest, comnet.minihadoop.common.message.cli.UploadRequest.Builder, comnet.minihadoop.common.message.cli.UploadRequestOrBuilder> 
        getUploadRequestFieldBuilder() {
      if (uploadRequestBuilder_ == null) {
        if (!(dataCase_ == 5)) {
          data_ = comnet.minihadoop.common.message.cli.UploadRequest.getDefaultInstance();
        }
        uploadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.UploadRequest, comnet.minihadoop.common.message.cli.UploadRequest.Builder, comnet.minihadoop.common.message.cli.UploadRequestOrBuilder>(
                (comnet.minihadoop.common.message.cli.UploadRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 5;
      onChanged();
      return uploadRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadResponse, comnet.minihadoop.common.message.cli.UploadResponse.Builder, comnet.minihadoop.common.message.cli.UploadResponseOrBuilder> uploadResponseBuilder_;
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     * @return Whether the uploadResponse field is set.
     */
    public boolean hasUploadResponse() {
      return dataCase_ == 6;
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     * @return The uploadResponse.
     */
    public comnet.minihadoop.common.message.cli.UploadResponse getUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (dataCase_ == 6) {
          return (comnet.minihadoop.common.message.cli.UploadResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
      } else {
        if (dataCase_ == 6) {
          return uploadResponseBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public Builder setUploadResponse(comnet.minihadoop.common.message.cli.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(value);
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public Builder setUploadResponse(
        comnet.minihadoop.common.message.cli.UploadResponse.Builder builderForValue) {
      if (uploadResponseBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public Builder mergeUploadResponse(comnet.minihadoop.common.message.cli.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (dataCase_ == 6 &&
            data_ != comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.UploadResponse.newBuilder((comnet.minihadoop.common.message.cli.UploadResponse) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 6) {
          uploadResponseBuilder_.mergeFrom(value);
        }
        uploadResponseBuilder_.setMessage(value);
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public Builder clearUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
        }
        uploadResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadResponse.Builder getUploadResponseBuilder() {
      return getUploadResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadResponseOrBuilder getUploadResponseOrBuilder() {
      if ((dataCase_ == 6) && (uploadResponseBuilder_ != null)) {
        return uploadResponseBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 6) {
          return (comnet.minihadoop.common.message.cli.UploadResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadResponse uploadResponse = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadResponse, comnet.minihadoop.common.message.cli.UploadResponse.Builder, comnet.minihadoop.common.message.cli.UploadResponseOrBuilder> 
        getUploadResponseFieldBuilder() {
      if (uploadResponseBuilder_ == null) {
        if (!(dataCase_ == 6)) {
          data_ = comnet.minihadoop.common.message.cli.UploadResponse.getDefaultInstance();
        }
        uploadResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.UploadResponse, comnet.minihadoop.common.message.cli.UploadResponse.Builder, comnet.minihadoop.common.message.cli.UploadResponseOrBuilder>(
                (comnet.minihadoop.common.message.cli.UploadResponse) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 6;
      onChanged();
      return uploadResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadReady, comnet.minihadoop.common.message.cli.UploadReady.Builder, comnet.minihadoop.common.message.cli.UploadReadyOrBuilder> uploadReadyBuilder_;
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     * @return Whether the uploadReady field is set.
     */
    public boolean hasUploadReady() {
      return dataCase_ == 7;
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     * @return The uploadReady.
     */
    public comnet.minihadoop.common.message.cli.UploadReady getUploadReady() {
      if (uploadReadyBuilder_ == null) {
        if (dataCase_ == 7) {
          return (comnet.minihadoop.common.message.cli.UploadReady) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
      } else {
        if (dataCase_ == 7) {
          return uploadReadyBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public Builder setUploadReady(comnet.minihadoop.common.message.cli.UploadReady value) {
      if (uploadReadyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        uploadReadyBuilder_.setMessage(value);
      }
      dataCase_ = 7;
      return this;
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public Builder setUploadReady(
        comnet.minihadoop.common.message.cli.UploadReady.Builder builderForValue) {
      if (uploadReadyBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        uploadReadyBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 7;
      return this;
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public Builder mergeUploadReady(comnet.minihadoop.common.message.cli.UploadReady value) {
      if (uploadReadyBuilder_ == null) {
        if (dataCase_ == 7 &&
            data_ != comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.UploadReady.newBuilder((comnet.minihadoop.common.message.cli.UploadReady) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 7) {
          uploadReadyBuilder_.mergeFrom(value);
        }
        uploadReadyBuilder_.setMessage(value);
      }
      dataCase_ = 7;
      return this;
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public Builder clearUploadReady() {
      if (uploadReadyBuilder_ == null) {
        if (dataCase_ == 7) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 7) {
          dataCase_ = 0;
          data_ = null;
        }
        uploadReadyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadReady.Builder getUploadReadyBuilder() {
      return getUploadReadyFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    public comnet.minihadoop.common.message.cli.UploadReadyOrBuilder getUploadReadyOrBuilder() {
      if ((dataCase_ == 7) && (uploadReadyBuilder_ != null)) {
        return uploadReadyBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 7) {
          return (comnet.minihadoop.common.message.cli.UploadReady) data_;
        }
        return comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.UploadReady uploadReady = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.UploadReady, comnet.minihadoop.common.message.cli.UploadReady.Builder, comnet.minihadoop.common.message.cli.UploadReadyOrBuilder> 
        getUploadReadyFieldBuilder() {
      if (uploadReadyBuilder_ == null) {
        if (!(dataCase_ == 7)) {
          data_ = comnet.minihadoop.common.message.cli.UploadReady.getDefaultInstance();
        }
        uploadReadyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.UploadReady, comnet.minihadoop.common.message.cli.UploadReady.Builder, comnet.minihadoop.common.message.cli.UploadReadyOrBuilder>(
                (comnet.minihadoop.common.message.cli.UploadReady) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 7;
      onChanged();
      return uploadReadyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.ListRequest, comnet.minihadoop.common.message.cli.ListRequest.Builder, comnet.minihadoop.common.message.cli.ListRequestOrBuilder> listRequestBuilder_;
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     * @return Whether the listRequest field is set.
     */
    public boolean hasListRequest() {
      return dataCase_ == 8;
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     * @return The listRequest.
     */
    public comnet.minihadoop.common.message.cli.ListRequest getListRequest() {
      if (listRequestBuilder_ == null) {
        if (dataCase_ == 8) {
          return (comnet.minihadoop.common.message.cli.ListRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 8) {
          return listRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public Builder setListRequest(comnet.minihadoop.common.message.cli.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        listRequestBuilder_.setMessage(value);
      }
      dataCase_ = 8;
      return this;
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public Builder setListRequest(
        comnet.minihadoop.common.message.cli.ListRequest.Builder builderForValue) {
      if (listRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        listRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 8;
      return this;
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public Builder mergeListRequest(comnet.minihadoop.common.message.cli.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (dataCase_ == 8 &&
            data_ != comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.ListRequest.newBuilder((comnet.minihadoop.common.message.cli.ListRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 8) {
          listRequestBuilder_.mergeFrom(value);
        }
        listRequestBuilder_.setMessage(value);
      }
      dataCase_ = 8;
      return this;
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public Builder clearListRequest() {
      if (listRequestBuilder_ == null) {
        if (dataCase_ == 8) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 8) {
          dataCase_ = 0;
          data_ = null;
        }
        listRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public comnet.minihadoop.common.message.cli.ListRequest.Builder getListRequestBuilder() {
      return getListRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    public comnet.minihadoop.common.message.cli.ListRequestOrBuilder getListRequestOrBuilder() {
      if ((dataCase_ == 8) && (listRequestBuilder_ != null)) {
        return listRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 8) {
          return (comnet.minihadoop.common.message.cli.ListRequest) data_;
        }
        return comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.ListRequest listRequest = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.ListRequest, comnet.minihadoop.common.message.cli.ListRequest.Builder, comnet.minihadoop.common.message.cli.ListRequestOrBuilder> 
        getListRequestFieldBuilder() {
      if (listRequestBuilder_ == null) {
        if (!(dataCase_ == 8)) {
          data_ = comnet.minihadoop.common.message.cli.ListRequest.getDefaultInstance();
        }
        listRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.ListRequest, comnet.minihadoop.common.message.cli.ListRequest.Builder, comnet.minihadoop.common.message.cli.ListRequestOrBuilder>(
                (comnet.minihadoop.common.message.cli.ListRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 8;
      onChanged();
      return listRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.ListResponse, comnet.minihadoop.common.message.cli.ListResponse.Builder, comnet.minihadoop.common.message.cli.ListResponseOrBuilder> listResponseBuilder_;
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     * @return Whether the listResponse field is set.
     */
    public boolean hasListResponse() {
      return dataCase_ == 9;
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     * @return The listResponse.
     */
    public comnet.minihadoop.common.message.cli.ListResponse getListResponse() {
      if (listResponseBuilder_ == null) {
        if (dataCase_ == 9) {
          return (comnet.minihadoop.common.message.cli.ListResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
      } else {
        if (dataCase_ == 9) {
          return listResponseBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public Builder setListResponse(comnet.minihadoop.common.message.cli.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        listResponseBuilder_.setMessage(value);
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public Builder setListResponse(
        comnet.minihadoop.common.message.cli.ListResponse.Builder builderForValue) {
      if (listResponseBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        listResponseBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public Builder mergeListResponse(comnet.minihadoop.common.message.cli.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (dataCase_ == 9 &&
            data_ != comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.cli.ListResponse.newBuilder((comnet.minihadoop.common.message.cli.ListResponse) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 9) {
          listResponseBuilder_.mergeFrom(value);
        }
        listResponseBuilder_.setMessage(value);
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public Builder clearListResponse() {
      if (listResponseBuilder_ == null) {
        if (dataCase_ == 9) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 9) {
          dataCase_ = 0;
          data_ = null;
        }
        listResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public comnet.minihadoop.common.message.cli.ListResponse.Builder getListResponseBuilder() {
      return getListResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    public comnet.minihadoop.common.message.cli.ListResponseOrBuilder getListResponseOrBuilder() {
      if ((dataCase_ == 9) && (listResponseBuilder_ != null)) {
        return listResponseBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 9) {
          return (comnet.minihadoop.common.message.cli.ListResponse) data_;
        }
        return comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.cli.ListResponse listResponse = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.cli.ListResponse, comnet.minihadoop.common.message.cli.ListResponse.Builder, comnet.minihadoop.common.message.cli.ListResponseOrBuilder> 
        getListResponseFieldBuilder() {
      if (listResponseBuilder_ == null) {
        if (!(dataCase_ == 9)) {
          data_ = comnet.minihadoop.common.message.cli.ListResponse.getDefaultInstance();
        }
        listResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.cli.ListResponse, comnet.minihadoop.common.message.cli.ListResponse.Builder, comnet.minihadoop.common.message.cli.ListResponseOrBuilder>(
                (comnet.minihadoop.common.message.cli.ListResponse) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 9;
      onChanged();
      return listResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cli.CLIMessage)
  }

  // @@protoc_insertion_point(class_scope:cli.CLIMessage)
  private static final comnet.minihadoop.common.message.cli.CLIMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new comnet.minihadoop.common.message.cli.CLIMessage();
  }

  public static comnet.minihadoop.common.message.cli.CLIMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CLIMessage>
      PARSER = new com.google.protobuf.AbstractParser<CLIMessage>() {
    @java.lang.Override
    public CLIMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CLIMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CLIMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CLIMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public comnet.minihadoop.common.message.cli.CLIMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

