// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/cli.proto

package comnet.minihadoop.common.message.cli;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cli.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ID = 1;</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1;</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();

  /**
   * <code>bytes password = 2;</code>
   * @return The password.
   */
  com.google.protobuf.ByteString getPassword();
}
