version: 1

#  master information
master-host: 192.168.35.97  # master address MUST be speified
master-welcome-port: 5050

# slave information
listening-port: 5051
health-check-port: 10001
data-dir: slave1data
master-discovery-timeout: 30 # in seconds for initial master connection