// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

public interface ConnectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slave.ConnectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ack = 1;</code>
   * @return The ack.
   */
  int getAck();

  /**
   * <code>int32 healthCheckPeriod = 2;</code>
   * @return The healthCheckPeriod.
   */
  int getHealthCheckPeriod();

  /**
   * <code>int32 healthCheckPort = 3;</code>
   * @return The healthCheckPort.
   */
  int getHealthCheckPort();
}
