// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

/**
 * Protobuf type {@code slave.ConnectionResponse}
 */
public  final class ConnectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slave.ConnectionResponse)
    ConnectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConnectionResponse.newBuilder() to construct.
  private ConnectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConnectionResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConnectionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConnectionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ack_ = input.readInt32();
            break;
          }
          case 16: {

            healthCheckPeriod_ = input.readInt32();
            break;
          }
          case 24: {

            healthCheckPort_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_ConnectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_ConnectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            comnet.minihadoop.common.message.slave.ConnectionResponse.class, comnet.minihadoop.common.message.slave.ConnectionResponse.Builder.class);
  }

  public static final int ACK_FIELD_NUMBER = 1;
  private int ack_;
  /**
   * <code>int32 ack = 1;</code>
   * @return The ack.
   */
  public int getAck() {
    return ack_;
  }

  public static final int HEALTHCHECKPERIOD_FIELD_NUMBER = 2;
  private int healthCheckPeriod_;
  /**
   * <code>int32 healthCheckPeriod = 2;</code>
   * @return The healthCheckPeriod.
   */
  public int getHealthCheckPeriod() {
    return healthCheckPeriod_;
  }

  public static final int HEALTHCHECKPORT_FIELD_NUMBER = 3;
  private int healthCheckPort_;
  /**
   * <code>int32 healthCheckPort = 3;</code>
   * @return The healthCheckPort.
   */
  public int getHealthCheckPort() {
    return healthCheckPort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ack_ != 0) {
      output.writeInt32(1, ack_);
    }
    if (healthCheckPeriod_ != 0) {
      output.writeInt32(2, healthCheckPeriod_);
    }
    if (healthCheckPort_ != 0) {
      output.writeInt32(3, healthCheckPort_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ack_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ack_);
    }
    if (healthCheckPeriod_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, healthCheckPeriod_);
    }
    if (healthCheckPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, healthCheckPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof comnet.minihadoop.common.message.slave.ConnectionResponse)) {
      return super.equals(obj);
    }
    comnet.minihadoop.common.message.slave.ConnectionResponse other = (comnet.minihadoop.common.message.slave.ConnectionResponse) obj;

    if (getAck()
        != other.getAck()) return false;
    if (getHealthCheckPeriod()
        != other.getHealthCheckPeriod()) return false;
    if (getHealthCheckPort()
        != other.getHealthCheckPort()) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACK_FIELD_NUMBER;
    hash = (53 * hash) + getAck();
    hash = (37 * hash) + HEALTHCHECKPERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getHealthCheckPeriod();
    hash = (37 * hash) + HEALTHCHECKPORT_FIELD_NUMBER;
    hash = (53 * hash) + getHealthCheckPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.ConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(comnet.minihadoop.common.message.slave.ConnectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slave.ConnectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slave.ConnectionResponse)
      comnet.minihadoop.common.message.slave.ConnectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_ConnectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_ConnectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comnet.minihadoop.common.message.slave.ConnectionResponse.class, comnet.minihadoop.common.message.slave.ConnectionResponse.Builder.class);
    }

    // Construct using comnet.minihadoop.common.message.slave.ConnectionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ack_ = 0;

      healthCheckPeriod_ = 0;

      healthCheckPort_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_ConnectionResponse_descriptor;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.ConnectionResponse getDefaultInstanceForType() {
      return comnet.minihadoop.common.message.slave.ConnectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.ConnectionResponse build() {
      comnet.minihadoop.common.message.slave.ConnectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.ConnectionResponse buildPartial() {
      comnet.minihadoop.common.message.slave.ConnectionResponse result = new comnet.minihadoop.common.message.slave.ConnectionResponse(this);
      result.ack_ = ack_;
      result.healthCheckPeriod_ = healthCheckPeriod_;
      result.healthCheckPort_ = healthCheckPort_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof comnet.minihadoop.common.message.slave.ConnectionResponse) {
        return mergeFrom((comnet.minihadoop.common.message.slave.ConnectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(comnet.minihadoop.common.message.slave.ConnectionResponse other) {
      if (other == comnet.minihadoop.common.message.slave.ConnectionResponse.getDefaultInstance()) return this;
      if (other.getAck() != 0) {
        setAck(other.getAck());
      }
      if (other.getHealthCheckPeriod() != 0) {
        setHealthCheckPeriod(other.getHealthCheckPeriod());
      }
      if (other.getHealthCheckPort() != 0) {
        setHealthCheckPort(other.getHealthCheckPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      comnet.minihadoop.common.message.slave.ConnectionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (comnet.minihadoop.common.message.slave.ConnectionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ack_ ;
    /**
     * <code>int32 ack = 1;</code>
     * @return The ack.
     */
    public int getAck() {
      return ack_;
    }
    /**
     * <code>int32 ack = 1;</code>
     * @param value The ack to set.
     * @return This builder for chaining.
     */
    public Builder setAck(int value) {
      
      ack_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ack = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAck() {
      
      ack_ = 0;
      onChanged();
      return this;
    }

    private int healthCheckPeriod_ ;
    /**
     * <code>int32 healthCheckPeriod = 2;</code>
     * @return The healthCheckPeriod.
     */
    public int getHealthCheckPeriod() {
      return healthCheckPeriod_;
    }
    /**
     * <code>int32 healthCheckPeriod = 2;</code>
     * @param value The healthCheckPeriod to set.
     * @return This builder for chaining.
     */
    public Builder setHealthCheckPeriod(int value) {
      
      healthCheckPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 healthCheckPeriod = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealthCheckPeriod() {
      
      healthCheckPeriod_ = 0;
      onChanged();
      return this;
    }

    private int healthCheckPort_ ;
    /**
     * <code>int32 healthCheckPort = 3;</code>
     * @return The healthCheckPort.
     */
    public int getHealthCheckPort() {
      return healthCheckPort_;
    }
    /**
     * <code>int32 healthCheckPort = 3;</code>
     * @param value The healthCheckPort to set.
     * @return This builder for chaining.
     */
    public Builder setHealthCheckPort(int value) {
      
      healthCheckPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 healthCheckPort = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealthCheckPort() {
      
      healthCheckPort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slave.ConnectionResponse)
  }

  // @@protoc_insertion_point(class_scope:slave.ConnectionResponse)
  private static final comnet.minihadoop.common.message.slave.ConnectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new comnet.minihadoop.common.message.slave.ConnectionResponse();
  }

  public static comnet.minihadoop.common.message.slave.ConnectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConnectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ConnectionResponse>() {
    @java.lang.Override
    public ConnectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConnectionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConnectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConnectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public comnet.minihadoop.common.message.slave.ConnectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

