// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

/**
 * Protobuf type {@code slave.Job}
 */
public  final class Job extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slave.Job)
    JobOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Job.newBuilder() to construct.
  private Job(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Job() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Job();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Job(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 130: {
            comnet.minihadoop.common.message.slave.UploadRequest.Builder subBuilder = null;
            if (dataCase_ == 16) {
              subBuilder = ((comnet.minihadoop.common.message.slave.UploadRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.slave.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.slave.UploadRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 16;
            break;
          }
          case 138: {
            comnet.minihadoop.common.message.slave.ReplicateRequest.Builder subBuilder = null;
            if (dataCase_ == 17) {
              subBuilder = ((comnet.minihadoop.common.message.slave.ReplicateRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.slave.ReplicateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.slave.ReplicateRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 17;
            break;
          }
          case 146: {
            comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder subBuilder = null;
            if (dataCase_ == 18) {
              subBuilder = ((comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.slave.ReplicateReadyRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 18;
            break;
          }
          case 154: {
            comnet.minihadoop.common.message.slave.ReplicateResponse.Builder subBuilder = null;
            if (dataCase_ == 19) {
              subBuilder = ((comnet.minihadoop.common.message.slave.ReplicateResponse) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.slave.ReplicateResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.slave.ReplicateResponse) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 19;
            break;
          }
          case 162: {
            comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder subBuilder = null;
            if (dataCase_ == 20) {
              subBuilder = ((comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_).toBuilder();
            }
            data_ =
                input.readMessage(comnet.minihadoop.common.message.slave.ReplicateReadyResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 20;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_Job_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_Job_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            comnet.minihadoop.common.message.slave.Job.class, comnet.minihadoop.common.message.slave.Job.Builder.class);
  }

  /**
   * Protobuf enum {@code slave.Job.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UPLOAD_REQ = 0;</code>
     */
    UPLOAD_REQ(0),
    /**
     * <code>REPLICATE_READY_REQ = 1;</code>
     */
    REPLICATE_READY_REQ(1),
    /**
     * <code>REPLICATE_REQ = 2;</code>
     */
    REPLICATE_REQ(2),
    /**
     * <code>REPLICATE_READY_RES = 3;</code>
     */
    REPLICATE_READY_RES(3),
    /**
     * <code>REPLICATE_RES = 4;</code>
     */
    REPLICATE_RES(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UPLOAD_REQ = 0;</code>
     */
    public static final int UPLOAD_REQ_VALUE = 0;
    /**
     * <code>REPLICATE_READY_REQ = 1;</code>
     */
    public static final int REPLICATE_READY_REQ_VALUE = 1;
    /**
     * <code>REPLICATE_REQ = 2;</code>
     */
    public static final int REPLICATE_REQ_VALUE = 2;
    /**
     * <code>REPLICATE_READY_RES = 3;</code>
     */
    public static final int REPLICATE_READY_RES_VALUE = 3;
    /**
     * <code>REPLICATE_RES = 4;</code>
     */
    public static final int REPLICATE_RES_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return UPLOAD_REQ;
        case 1: return REPLICATE_READY_REQ;
        case 2: return REPLICATE_REQ;
        case 3: return REPLICATE_READY_RES;
        case 4: return REPLICATE_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.slave.Job.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:slave.Job.Type)
  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UPLOADREQUEST(16),
    REPLICATEREQUEST(17),
    REPLICATIONREADYREQUEST(18),
    REPLICATERESPONSE(19),
    REPLICATIONREADYRESPONSE(20),
    DATA_NOT_SET(0);
    private final int value;
    DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 16: return UPLOADREQUEST;
        case 17: return REPLICATEREQUEST;
        case 18: return REPLICATIONREADYREQUEST;
        case 19: return REPLICATERESPONSE;
        case 20: return REPLICATIONREADYRESPONSE;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  }

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.slave.Job.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.slave.Job.Type type = 1;</code>
   * @return The type.
   */
  public comnet.minihadoop.common.message.slave.Job.Type getType() {
    @SuppressWarnings("deprecation")
    comnet.minihadoop.common.message.slave.Job.Type result = comnet.minihadoop.common.message.slave.Job.Type.valueOf(type_);
    return result == null ? comnet.minihadoop.common.message.slave.Job.Type.UNRECOGNIZED : result;
  }

  public static final int UPLOADREQUEST_FIELD_NUMBER = 16;
  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   * @return Whether the uploadRequest field is set.
   */
  public boolean hasUploadRequest() {
    return dataCase_ == 16;
  }
  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   * @return The uploadRequest.
   */
  public comnet.minihadoop.common.message.slave.UploadRequest getUploadRequest() {
    if (dataCase_ == 16) {
       return (comnet.minihadoop.common.message.slave.UploadRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
  }
  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   */
  public comnet.minihadoop.common.message.slave.UploadRequestOrBuilder getUploadRequestOrBuilder() {
    if (dataCase_ == 16) {
       return (comnet.minihadoop.common.message.slave.UploadRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
  }

  public static final int REPLICATEREQUEST_FIELD_NUMBER = 17;
  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   * @return Whether the replicateRequest field is set.
   */
  public boolean hasReplicateRequest() {
    return dataCase_ == 17;
  }
  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   * @return The replicateRequest.
   */
  public comnet.minihadoop.common.message.slave.ReplicateRequest getReplicateRequest() {
    if (dataCase_ == 17) {
       return (comnet.minihadoop.common.message.slave.ReplicateRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
  }
  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   */
  public comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder getReplicateRequestOrBuilder() {
    if (dataCase_ == 17) {
       return (comnet.minihadoop.common.message.slave.ReplicateRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
  }

  public static final int REPLICATIONREADYREQUEST_FIELD_NUMBER = 18;
  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   * @return Whether the replicationReadyRequest field is set.
   */
  public boolean hasReplicationReadyRequest() {
    return dataCase_ == 18;
  }
  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   * @return The replicationReadyRequest.
   */
  public comnet.minihadoop.common.message.slave.ReplicateReadyRequest getReplicationReadyRequest() {
    if (dataCase_ == 18) {
       return (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
  }
  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   */
  public comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder getReplicationReadyRequestOrBuilder() {
    if (dataCase_ == 18) {
       return (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
  }

  public static final int REPLICATERESPONSE_FIELD_NUMBER = 19;
  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   * @return Whether the replicateResponse field is set.
   */
  public boolean hasReplicateResponse() {
    return dataCase_ == 19;
  }
  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   * @return The replicateResponse.
   */
  public comnet.minihadoop.common.message.slave.ReplicateResponse getReplicateResponse() {
    if (dataCase_ == 19) {
       return (comnet.minihadoop.common.message.slave.ReplicateResponse) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
  }
  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   */
  public comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder getReplicateResponseOrBuilder() {
    if (dataCase_ == 19) {
       return (comnet.minihadoop.common.message.slave.ReplicateResponse) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
  }

  public static final int REPLICATIONREADYRESPONSE_FIELD_NUMBER = 20;
  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   * @return Whether the replicationReadyResponse field is set.
   */
  public boolean hasReplicationReadyResponse() {
    return dataCase_ == 20;
  }
  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   * @return The replicationReadyResponse.
   */
  public comnet.minihadoop.common.message.slave.ReplicateReadyResponse getReplicationReadyResponse() {
    if (dataCase_ == 20) {
       return (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
  }
  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   */
  public comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder getReplicationReadyResponseOrBuilder() {
    if (dataCase_ == 20) {
       return (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_;
    }
    return comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != comnet.minihadoop.common.message.slave.Job.Type.UPLOAD_REQ.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (dataCase_ == 16) {
      output.writeMessage(16, (comnet.minihadoop.common.message.slave.UploadRequest) data_);
    }
    if (dataCase_ == 17) {
      output.writeMessage(17, (comnet.minihadoop.common.message.slave.ReplicateRequest) data_);
    }
    if (dataCase_ == 18) {
      output.writeMessage(18, (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_);
    }
    if (dataCase_ == 19) {
      output.writeMessage(19, (comnet.minihadoop.common.message.slave.ReplicateResponse) data_);
    }
    if (dataCase_ == 20) {
      output.writeMessage(20, (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != comnet.minihadoop.common.message.slave.Job.Type.UPLOAD_REQ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (dataCase_ == 16) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, (comnet.minihadoop.common.message.slave.UploadRequest) data_);
    }
    if (dataCase_ == 17) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, (comnet.minihadoop.common.message.slave.ReplicateRequest) data_);
    }
    if (dataCase_ == 18) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_);
    }
    if (dataCase_ == 19) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, (comnet.minihadoop.common.message.slave.ReplicateResponse) data_);
    }
    if (dataCase_ == 20) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof comnet.minihadoop.common.message.slave.Job)) {
      return super.equals(obj);
    }
    comnet.minihadoop.common.message.slave.Job other = (comnet.minihadoop.common.message.slave.Job) obj;

    if (type_ != other.type_) return false;
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 16:
        if (!getUploadRequest()
            .equals(other.getUploadRequest())) return false;
        break;
      case 17:
        if (!getReplicateRequest()
            .equals(other.getReplicateRequest())) return false;
        break;
      case 18:
        if (!getReplicationReadyRequest()
            .equals(other.getReplicationReadyRequest())) return false;
        break;
      case 19:
        if (!getReplicateResponse()
            .equals(other.getReplicateResponse())) return false;
        break;
      case 20:
        if (!getReplicationReadyResponse()
            .equals(other.getReplicationReadyResponse())) return false;
        break;
      case 0:
      default:
    }
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (dataCase_) {
      case 16:
        hash = (37 * hash) + UPLOADREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUploadRequest().hashCode();
        break;
      case 17:
        hash = (37 * hash) + REPLICATEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getReplicateRequest().hashCode();
        break;
      case 18:
        hash = (37 * hash) + REPLICATIONREADYREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getReplicationReadyRequest().hashCode();
        break;
      case 19:
        hash = (37 * hash) + REPLICATERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getReplicateResponse().hashCode();
        break;
      case 20:
        hash = (37 * hash) + REPLICATIONREADYRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getReplicationReadyResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.Job parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.Job parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.Job parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(comnet.minihadoop.common.message.slave.Job prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slave.Job}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slave.Job)
      comnet.minihadoop.common.message.slave.JobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_Job_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comnet.minihadoop.common.message.slave.Job.class, comnet.minihadoop.common.message.slave.Job.Builder.class);
    }

    // Construct using comnet.minihadoop.common.message.slave.Job.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_Job_descriptor;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.Job getDefaultInstanceForType() {
      return comnet.minihadoop.common.message.slave.Job.getDefaultInstance();
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.Job build() {
      comnet.minihadoop.common.message.slave.Job result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.Job buildPartial() {
      comnet.minihadoop.common.message.slave.Job result = new comnet.minihadoop.common.message.slave.Job(this);
      result.type_ = type_;
      if (dataCase_ == 16) {
        if (uploadRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = uploadRequestBuilder_.build();
        }
      }
      if (dataCase_ == 17) {
        if (replicateRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = replicateRequestBuilder_.build();
        }
      }
      if (dataCase_ == 18) {
        if (replicationReadyRequestBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = replicationReadyRequestBuilder_.build();
        }
      }
      if (dataCase_ == 19) {
        if (replicateResponseBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = replicateResponseBuilder_.build();
        }
      }
      if (dataCase_ == 20) {
        if (replicationReadyResponseBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = replicationReadyResponseBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof comnet.minihadoop.common.message.slave.Job) {
        return mergeFrom((comnet.minihadoop.common.message.slave.Job)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(comnet.minihadoop.common.message.slave.Job other) {
      if (other == comnet.minihadoop.common.message.slave.Job.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getDataCase()) {
        case UPLOADREQUEST: {
          mergeUploadRequest(other.getUploadRequest());
          break;
        }
        case REPLICATEREQUEST: {
          mergeReplicateRequest(other.getReplicateRequest());
          break;
        }
        case REPLICATIONREADYREQUEST: {
          mergeReplicationReadyRequest(other.getReplicationReadyRequest());
          break;
        }
        case REPLICATERESPONSE: {
          mergeReplicateResponse(other.getReplicateResponse());
          break;
        }
        case REPLICATIONREADYRESPONSE: {
          mergeReplicationReadyResponse(other.getReplicationReadyResponse());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      comnet.minihadoop.common.message.slave.Job parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (comnet.minihadoop.common.message.slave.Job) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.slave.Job.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.slave.Job.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.slave.Job.Type type = 1;</code>
     * @return The type.
     */
    public comnet.minihadoop.common.message.slave.Job.Type getType() {
      @SuppressWarnings("deprecation")
      comnet.minihadoop.common.message.slave.Job.Type result = comnet.minihadoop.common.message.slave.Job.Type.valueOf(type_);
      return result == null ? comnet.minihadoop.common.message.slave.Job.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.slave.Job.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(comnet.minihadoop.common.message.slave.Job.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.slave.Job.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.UploadRequest, comnet.minihadoop.common.message.slave.UploadRequest.Builder, comnet.minihadoop.common.message.slave.UploadRequestOrBuilder> uploadRequestBuilder_;
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     * @return Whether the uploadRequest field is set.
     */
    public boolean hasUploadRequest() {
      return dataCase_ == 16;
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     * @return The uploadRequest.
     */
    public comnet.minihadoop.common.message.slave.UploadRequest getUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 16) {
          return (comnet.minihadoop.common.message.slave.UploadRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 16) {
          return uploadRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public Builder setUploadRequest(comnet.minihadoop.common.message.slave.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(value);
      }
      dataCase_ = 16;
      return this;
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public Builder setUploadRequest(
        comnet.minihadoop.common.message.slave.UploadRequest.Builder builderForValue) {
      if (uploadRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 16;
      return this;
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public Builder mergeUploadRequest(comnet.minihadoop.common.message.slave.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 16 &&
            data_ != comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.slave.UploadRequest.newBuilder((comnet.minihadoop.common.message.slave.UploadRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 16) {
          uploadRequestBuilder_.mergeFrom(value);
        }
        uploadRequestBuilder_.setMessage(value);
      }
      dataCase_ = 16;
      return this;
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public Builder clearUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (dataCase_ == 16) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 16) {
          dataCase_ = 0;
          data_ = null;
        }
        uploadRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public comnet.minihadoop.common.message.slave.UploadRequest.Builder getUploadRequestBuilder() {
      return getUploadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    public comnet.minihadoop.common.message.slave.UploadRequestOrBuilder getUploadRequestOrBuilder() {
      if ((dataCase_ == 16) && (uploadRequestBuilder_ != null)) {
        return uploadRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 16) {
          return (comnet.minihadoop.common.message.slave.UploadRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.UploadRequest uploadRequest = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.UploadRequest, comnet.minihadoop.common.message.slave.UploadRequest.Builder, comnet.minihadoop.common.message.slave.UploadRequestOrBuilder> 
        getUploadRequestFieldBuilder() {
      if (uploadRequestBuilder_ == null) {
        if (!(dataCase_ == 16)) {
          data_ = comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
        }
        uploadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.slave.UploadRequest, comnet.minihadoop.common.message.slave.UploadRequest.Builder, comnet.minihadoop.common.message.slave.UploadRequestOrBuilder>(
                (comnet.minihadoop.common.message.slave.UploadRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 16;
      onChanged();
      return uploadRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateRequest, comnet.minihadoop.common.message.slave.ReplicateRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder> replicateRequestBuilder_;
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     * @return Whether the replicateRequest field is set.
     */
    public boolean hasReplicateRequest() {
      return dataCase_ == 17;
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     * @return The replicateRequest.
     */
    public comnet.minihadoop.common.message.slave.ReplicateRequest getReplicateRequest() {
      if (replicateRequestBuilder_ == null) {
        if (dataCase_ == 17) {
          return (comnet.minihadoop.common.message.slave.ReplicateRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 17) {
          return replicateRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public Builder setReplicateRequest(comnet.minihadoop.common.message.slave.ReplicateRequest value) {
      if (replicateRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        replicateRequestBuilder_.setMessage(value);
      }
      dataCase_ = 17;
      return this;
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public Builder setReplicateRequest(
        comnet.minihadoop.common.message.slave.ReplicateRequest.Builder builderForValue) {
      if (replicateRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        replicateRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 17;
      return this;
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public Builder mergeReplicateRequest(comnet.minihadoop.common.message.slave.ReplicateRequest value) {
      if (replicateRequestBuilder_ == null) {
        if (dataCase_ == 17 &&
            data_ != comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateRequest.newBuilder((comnet.minihadoop.common.message.slave.ReplicateRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 17) {
          replicateRequestBuilder_.mergeFrom(value);
        }
        replicateRequestBuilder_.setMessage(value);
      }
      dataCase_ = 17;
      return this;
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public Builder clearReplicateRequest() {
      if (replicateRequestBuilder_ == null) {
        if (dataCase_ == 17) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 17) {
          dataCase_ = 0;
          data_ = null;
        }
        replicateRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateRequest.Builder getReplicateRequestBuilder() {
      return getReplicateRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder getReplicateRequestOrBuilder() {
      if ((dataCase_ == 17) && (replicateRequestBuilder_ != null)) {
        return replicateRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 17) {
          return (comnet.minihadoop.common.message.slave.ReplicateRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateRequest, comnet.minihadoop.common.message.slave.ReplicateRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder> 
        getReplicateRequestFieldBuilder() {
      if (replicateRequestBuilder_ == null) {
        if (!(dataCase_ == 17)) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateRequest.getDefaultInstance();
        }
        replicateRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.slave.ReplicateRequest, comnet.minihadoop.common.message.slave.ReplicateRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder>(
                (comnet.minihadoop.common.message.slave.ReplicateRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 17;
      onChanged();
      return replicateRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateReadyRequest, comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder> replicationReadyRequestBuilder_;
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     * @return Whether the replicationReadyRequest field is set.
     */
    public boolean hasReplicationReadyRequest() {
      return dataCase_ == 18;
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     * @return The replicationReadyRequest.
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyRequest getReplicationReadyRequest() {
      if (replicationReadyRequestBuilder_ == null) {
        if (dataCase_ == 18) {
          return (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
      } else {
        if (dataCase_ == 18) {
          return replicationReadyRequestBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public Builder setReplicationReadyRequest(comnet.minihadoop.common.message.slave.ReplicateReadyRequest value) {
      if (replicationReadyRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        replicationReadyRequestBuilder_.setMessage(value);
      }
      dataCase_ = 18;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public Builder setReplicationReadyRequest(
        comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder builderForValue) {
      if (replicationReadyRequestBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        replicationReadyRequestBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 18;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public Builder mergeReplicationReadyRequest(comnet.minihadoop.common.message.slave.ReplicateReadyRequest value) {
      if (replicationReadyRequestBuilder_ == null) {
        if (dataCase_ == 18 &&
            data_ != comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateReadyRequest.newBuilder((comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 18) {
          replicationReadyRequestBuilder_.mergeFrom(value);
        }
        replicationReadyRequestBuilder_.setMessage(value);
      }
      dataCase_ = 18;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public Builder clearReplicationReadyRequest() {
      if (replicationReadyRequestBuilder_ == null) {
        if (dataCase_ == 18) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 18) {
          dataCase_ = 0;
          data_ = null;
        }
        replicationReadyRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder getReplicationReadyRequestBuilder() {
      return getReplicationReadyRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder getReplicationReadyRequestOrBuilder() {
      if ((dataCase_ == 18) && (replicationReadyRequestBuilder_ != null)) {
        return replicationReadyRequestBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 18) {
          return (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateReadyRequest, comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder> 
        getReplicationReadyRequestFieldBuilder() {
      if (replicationReadyRequestBuilder_ == null) {
        if (!(dataCase_ == 18)) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateReadyRequest.getDefaultInstance();
        }
        replicationReadyRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.slave.ReplicateReadyRequest, comnet.minihadoop.common.message.slave.ReplicateReadyRequest.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder>(
                (comnet.minihadoop.common.message.slave.ReplicateReadyRequest) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 18;
      onChanged();
      return replicationReadyRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateResponse, comnet.minihadoop.common.message.slave.ReplicateResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder> replicateResponseBuilder_;
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     * @return Whether the replicateResponse field is set.
     */
    public boolean hasReplicateResponse() {
      return dataCase_ == 19;
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     * @return The replicateResponse.
     */
    public comnet.minihadoop.common.message.slave.ReplicateResponse getReplicateResponse() {
      if (replicateResponseBuilder_ == null) {
        if (dataCase_ == 19) {
          return (comnet.minihadoop.common.message.slave.ReplicateResponse) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
      } else {
        if (dataCase_ == 19) {
          return replicateResponseBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public Builder setReplicateResponse(comnet.minihadoop.common.message.slave.ReplicateResponse value) {
      if (replicateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        replicateResponseBuilder_.setMessage(value);
      }
      dataCase_ = 19;
      return this;
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public Builder setReplicateResponse(
        comnet.minihadoop.common.message.slave.ReplicateResponse.Builder builderForValue) {
      if (replicateResponseBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        replicateResponseBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 19;
      return this;
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public Builder mergeReplicateResponse(comnet.minihadoop.common.message.slave.ReplicateResponse value) {
      if (replicateResponseBuilder_ == null) {
        if (dataCase_ == 19 &&
            data_ != comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateResponse.newBuilder((comnet.minihadoop.common.message.slave.ReplicateResponse) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 19) {
          replicateResponseBuilder_.mergeFrom(value);
        }
        replicateResponseBuilder_.setMessage(value);
      }
      dataCase_ = 19;
      return this;
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public Builder clearReplicateResponse() {
      if (replicateResponseBuilder_ == null) {
        if (dataCase_ == 19) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 19) {
          dataCase_ = 0;
          data_ = null;
        }
        replicateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateResponse.Builder getReplicateResponseBuilder() {
      return getReplicateResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder getReplicateResponseOrBuilder() {
      if ((dataCase_ == 19) && (replicateResponseBuilder_ != null)) {
        return replicateResponseBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 19) {
          return (comnet.minihadoop.common.message.slave.ReplicateResponse) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateResponse, comnet.minihadoop.common.message.slave.ReplicateResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder> 
        getReplicateResponseFieldBuilder() {
      if (replicateResponseBuilder_ == null) {
        if (!(dataCase_ == 19)) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateResponse.getDefaultInstance();
        }
        replicateResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.slave.ReplicateResponse, comnet.minihadoop.common.message.slave.ReplicateResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder>(
                (comnet.minihadoop.common.message.slave.ReplicateResponse) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 19;
      onChanged();
      return replicateResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateReadyResponse, comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder> replicationReadyResponseBuilder_;
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     * @return Whether the replicationReadyResponse field is set.
     */
    public boolean hasReplicationReadyResponse() {
      return dataCase_ == 20;
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     * @return The replicationReadyResponse.
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyResponse getReplicationReadyResponse() {
      if (replicationReadyResponseBuilder_ == null) {
        if (dataCase_ == 20) {
          return (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
      } else {
        if (dataCase_ == 20) {
          return replicationReadyResponseBuilder_.getMessage();
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public Builder setReplicationReadyResponse(comnet.minihadoop.common.message.slave.ReplicateReadyResponse value) {
      if (replicationReadyResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        replicationReadyResponseBuilder_.setMessage(value);
      }
      dataCase_ = 20;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public Builder setReplicationReadyResponse(
        comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder builderForValue) {
      if (replicationReadyResponseBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        replicationReadyResponseBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 20;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public Builder mergeReplicationReadyResponse(comnet.minihadoop.common.message.slave.ReplicateReadyResponse value) {
      if (replicationReadyResponseBuilder_ == null) {
        if (dataCase_ == 20 &&
            data_ != comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance()) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateReadyResponse.newBuilder((comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 20) {
          replicationReadyResponseBuilder_.mergeFrom(value);
        }
        replicationReadyResponseBuilder_.setMessage(value);
      }
      dataCase_ = 20;
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public Builder clearReplicationReadyResponse() {
      if (replicationReadyResponseBuilder_ == null) {
        if (dataCase_ == 20) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 20) {
          dataCase_ = 0;
          data_ = null;
        }
        replicationReadyResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder getReplicationReadyResponseBuilder() {
      return getReplicationReadyResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    public comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder getReplicationReadyResponseOrBuilder() {
      if ((dataCase_ == 20) && (replicationReadyResponseBuilder_ != null)) {
        return replicationReadyResponseBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 20) {
          return (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_;
        }
        return comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        comnet.minihadoop.common.message.slave.ReplicateReadyResponse, comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder> 
        getReplicationReadyResponseFieldBuilder() {
      if (replicationReadyResponseBuilder_ == null) {
        if (!(dataCase_ == 20)) {
          data_ = comnet.minihadoop.common.message.slave.ReplicateReadyResponse.getDefaultInstance();
        }
        replicationReadyResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            comnet.minihadoop.common.message.slave.ReplicateReadyResponse, comnet.minihadoop.common.message.slave.ReplicateReadyResponse.Builder, comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder>(
                (comnet.minihadoop.common.message.slave.ReplicateReadyResponse) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 20;
      onChanged();
      return replicationReadyResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slave.Job)
  }

  // @@protoc_insertion_point(class_scope:slave.Job)
  private static final comnet.minihadoop.common.message.slave.Job DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new comnet.minihadoop.common.message.slave.Job();
  }

  public static comnet.minihadoop.common.message.slave.Job getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Job>
      PARSER = new com.google.protobuf.AbstractParser<Job>() {
    @java.lang.Override
    public Job parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Job(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Job> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Job> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public comnet.minihadoop.common.message.slave.Job getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

