// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slave.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.slave.Job.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.slave.Job.Type type = 1;</code>
   * @return The type.
   */
  comnet.minihadoop.common.message.slave.Job.Type getType();

  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   * @return Whether the uploadRequest field is set.
   */
  boolean hasUploadRequest();
  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   * @return The uploadRequest.
   */
  comnet.minihadoop.common.message.slave.UploadRequest getUploadRequest();
  /**
   * <code>.slave.UploadRequest uploadRequest = 16;</code>
   */
  comnet.minihadoop.common.message.slave.UploadRequestOrBuilder getUploadRequestOrBuilder();

  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   * @return Whether the replicateRequest field is set.
   */
  boolean hasReplicateRequest();
  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   * @return The replicateRequest.
   */
  comnet.minihadoop.common.message.slave.ReplicateRequest getReplicateRequest();
  /**
   * <code>.slave.ReplicateRequest replicateRequest = 17;</code>
   */
  comnet.minihadoop.common.message.slave.ReplicateRequestOrBuilder getReplicateRequestOrBuilder();

  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   * @return Whether the replicationReadyRequest field is set.
   */
  boolean hasReplicationReadyRequest();
  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   * @return The replicationReadyRequest.
   */
  comnet.minihadoop.common.message.slave.ReplicateReadyRequest getReplicationReadyRequest();
  /**
   * <code>.slave.ReplicateReadyRequest replicationReadyRequest = 18;</code>
   */
  comnet.minihadoop.common.message.slave.ReplicateReadyRequestOrBuilder getReplicationReadyRequestOrBuilder();

  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   * @return Whether the replicateResponse field is set.
   */
  boolean hasReplicateResponse();
  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   * @return The replicateResponse.
   */
  comnet.minihadoop.common.message.slave.ReplicateResponse getReplicateResponse();
  /**
   * <code>.slave.ReplicateResponse replicateResponse = 19;</code>
   */
  comnet.minihadoop.common.message.slave.ReplicateResponseOrBuilder getReplicateResponseOrBuilder();

  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   * @return Whether the replicationReadyResponse field is set.
   */
  boolean hasReplicationReadyResponse();
  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   * @return The replicationReadyResponse.
   */
  comnet.minihadoop.common.message.slave.ReplicateReadyResponse getReplicationReadyResponse();
  /**
   * <code>.slave.ReplicateReadyResponse replicationReadyResponse = 20;</code>
   */
  comnet.minihadoop.common.message.slave.ReplicateReadyResponseOrBuilder getReplicationReadyResponseOrBuilder();

  comnet.minihadoop.common.message.slave.Job.DataCase getDataCase();
}
