// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

public interface ReplicateReadyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slave.ReplicateReadyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string userID = 4;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 4;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();
}
