// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

public interface ReplicateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slave.ReplicateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostname = 1;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 1;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string userID = 4;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 4;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();
}
