// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

public interface UploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slave.UploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.slave.UploadResponse.Type status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.slave.UploadResponse.Type status = 1;</code>
   * @return The status.
   */
  comnet.minihadoop.common.message.slave.UploadResponse.Type getStatus();
}
