// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/slave.proto

package comnet.minihadoop.common.message.slave;

/**
 * Protobuf type {@code slave.UploadRequest}
 */
public  final class UploadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slave.UploadRequest)
    UploadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadRequest.newBuilder() to construct.
  private UploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadRequest() {
    clientHostname_ = "";
    filename_ = "";
    userID_ = "";
    slave1Hostname_ = "";
    slave2Hostname_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UploadRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientHostname_ = s;
            break;
          }
          case 16: {

            clientPort_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userID_ = s;
            break;
          }
          case 40: {

            initial_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            slave1Hostname_ = s;
            break;
          }
          case 56: {

            slave1Port_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            slave2Hostname_ = s;
            break;
          }
          case 72: {

            slave2Port_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_UploadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_UploadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            comnet.minihadoop.common.message.slave.UploadRequest.class, comnet.minihadoop.common.message.slave.UploadRequest.Builder.class);
  }

  public static final int CLIENTHOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientHostname_;
  /**
   * <code>string clientHostname = 1;</code>
   * @return The clientHostname.
   */
  public java.lang.String getClientHostname() {
    java.lang.Object ref = clientHostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientHostname_ = s;
      return s;
    }
  }
  /**
   * <code>string clientHostname = 1;</code>
   * @return The bytes for clientHostname.
   */
  public com.google.protobuf.ByteString
      getClientHostnameBytes() {
    java.lang.Object ref = clientHostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientHostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTPORT_FIELD_NUMBER = 2;
  private int clientPort_;
  /**
   * <code>int32 clientPort = 2;</code>
   * @return The clientPort.
   */
  public int getClientPort() {
    return clientPort_;
  }

  public static final int FILENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object filename_;
  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private volatile java.lang.Object userID_;
  /**
   * <code>string userID = 4;</code>
   * @return The userID.
   */
  public java.lang.String getUserID() {
    java.lang.Object ref = userID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userID_ = s;
      return s;
    }
  }
  /**
   * <code>string userID = 4;</code>
   * @return The bytes for userID.
   */
  public com.google.protobuf.ByteString
      getUserIDBytes() {
    java.lang.Object ref = userID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIAL_FIELD_NUMBER = 5;
  private boolean initial_;
  /**
   * <code>bool initial = 5;</code>
   * @return The initial.
   */
  public boolean getInitial() {
    return initial_;
  }

  public static final int SLAVE1HOSTNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object slave1Hostname_;
  /**
   * <code>string slave1Hostname = 6;</code>
   * @return The slave1Hostname.
   */
  public java.lang.String getSlave1Hostname() {
    java.lang.Object ref = slave1Hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slave1Hostname_ = s;
      return s;
    }
  }
  /**
   * <code>string slave1Hostname = 6;</code>
   * @return The bytes for slave1Hostname.
   */
  public com.google.protobuf.ByteString
      getSlave1HostnameBytes() {
    java.lang.Object ref = slave1Hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slave1Hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLAVE1PORT_FIELD_NUMBER = 7;
  private int slave1Port_;
  /**
   * <code>int32 slave1Port = 7;</code>
   * @return The slave1Port.
   */
  public int getSlave1Port() {
    return slave1Port_;
  }

  public static final int SLAVE2HOSTNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object slave2Hostname_;
  /**
   * <code>string slave2Hostname = 8;</code>
   * @return The slave2Hostname.
   */
  public java.lang.String getSlave2Hostname() {
    java.lang.Object ref = slave2Hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slave2Hostname_ = s;
      return s;
    }
  }
  /**
   * <code>string slave2Hostname = 8;</code>
   * @return The bytes for slave2Hostname.
   */
  public com.google.protobuf.ByteString
      getSlave2HostnameBytes() {
    java.lang.Object ref = slave2Hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slave2Hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLAVE2PORT_FIELD_NUMBER = 9;
  private int slave2Port_;
  /**
   * <code>int32 slave2Port = 9;</code>
   * @return The slave2Port.
   */
  public int getSlave2Port() {
    return slave2Port_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientHostname_);
    }
    if (clientPort_ != 0) {
      output.writeInt32(2, clientPort_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filename_);
    }
    if (!getUserIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userID_);
    }
    if (initial_ != false) {
      output.writeBool(5, initial_);
    }
    if (!getSlave1HostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, slave1Hostname_);
    }
    if (slave1Port_ != 0) {
      output.writeInt32(7, slave1Port_);
    }
    if (!getSlave2HostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, slave2Hostname_);
    }
    if (slave2Port_ != 0) {
      output.writeInt32(9, slave2Port_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientHostname_);
    }
    if (clientPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, clientPort_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filename_);
    }
    if (!getUserIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userID_);
    }
    if (initial_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, initial_);
    }
    if (!getSlave1HostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, slave1Hostname_);
    }
    if (slave1Port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, slave1Port_);
    }
    if (!getSlave2HostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, slave2Hostname_);
    }
    if (slave2Port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, slave2Port_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof comnet.minihadoop.common.message.slave.UploadRequest)) {
      return super.equals(obj);
    }
    comnet.minihadoop.common.message.slave.UploadRequest other = (comnet.minihadoop.common.message.slave.UploadRequest) obj;

    if (!getClientHostname()
        .equals(other.getClientHostname())) return false;
    if (getClientPort()
        != other.getClientPort()) return false;
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getUserID()
        .equals(other.getUserID())) return false;
    if (getInitial()
        != other.getInitial()) return false;
    if (!getSlave1Hostname()
        .equals(other.getSlave1Hostname())) return false;
    if (getSlave1Port()
        != other.getSlave1Port()) return false;
    if (!getSlave2Hostname()
        .equals(other.getSlave2Hostname())) return false;
    if (getSlave2Port()
        != other.getSlave2Port()) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTHOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientHostname().hashCode();
    hash = (37 * hash) + CLIENTPORT_FIELD_NUMBER;
    hash = (53 * hash) + getClientPort();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserID().hashCode();
    hash = (37 * hash) + INITIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInitial());
    hash = (37 * hash) + SLAVE1HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSlave1Hostname().hashCode();
    hash = (37 * hash) + SLAVE1PORT_FIELD_NUMBER;
    hash = (53 * hash) + getSlave1Port();
    hash = (37 * hash) + SLAVE2HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSlave2Hostname().hashCode();
    hash = (37 * hash) + SLAVE2PORT_FIELD_NUMBER;
    hash = (53 * hash) + getSlave2Port();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static comnet.minihadoop.common.message.slave.UploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(comnet.minihadoop.common.message.slave.UploadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slave.UploadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slave.UploadRequest)
      comnet.minihadoop.common.message.slave.UploadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_UploadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_UploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comnet.minihadoop.common.message.slave.UploadRequest.class, comnet.minihadoop.common.message.slave.UploadRequest.Builder.class);
    }

    // Construct using comnet.minihadoop.common.message.slave.UploadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientHostname_ = "";

      clientPort_ = 0;

      filename_ = "";

      userID_ = "";

      initial_ = false;

      slave1Hostname_ = "";

      slave1Port_ = 0;

      slave2Hostname_ = "";

      slave2Port_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return comnet.minihadoop.common.message.slave.Slave.internal_static_slave_UploadRequest_descriptor;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.UploadRequest getDefaultInstanceForType() {
      return comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.UploadRequest build() {
      comnet.minihadoop.common.message.slave.UploadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public comnet.minihadoop.common.message.slave.UploadRequest buildPartial() {
      comnet.minihadoop.common.message.slave.UploadRequest result = new comnet.minihadoop.common.message.slave.UploadRequest(this);
      result.clientHostname_ = clientHostname_;
      result.clientPort_ = clientPort_;
      result.filename_ = filename_;
      result.userID_ = userID_;
      result.initial_ = initial_;
      result.slave1Hostname_ = slave1Hostname_;
      result.slave1Port_ = slave1Port_;
      result.slave2Hostname_ = slave2Hostname_;
      result.slave2Port_ = slave2Port_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof comnet.minihadoop.common.message.slave.UploadRequest) {
        return mergeFrom((comnet.minihadoop.common.message.slave.UploadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(comnet.minihadoop.common.message.slave.UploadRequest other) {
      if (other == comnet.minihadoop.common.message.slave.UploadRequest.getDefaultInstance()) return this;
      if (!other.getClientHostname().isEmpty()) {
        clientHostname_ = other.clientHostname_;
        onChanged();
      }
      if (other.getClientPort() != 0) {
        setClientPort(other.getClientPort());
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (!other.getUserID().isEmpty()) {
        userID_ = other.userID_;
        onChanged();
      }
      if (other.getInitial() != false) {
        setInitial(other.getInitial());
      }
      if (!other.getSlave1Hostname().isEmpty()) {
        slave1Hostname_ = other.slave1Hostname_;
        onChanged();
      }
      if (other.getSlave1Port() != 0) {
        setSlave1Port(other.getSlave1Port());
      }
      if (!other.getSlave2Hostname().isEmpty()) {
        slave2Hostname_ = other.slave2Hostname_;
        onChanged();
      }
      if (other.getSlave2Port() != 0) {
        setSlave2Port(other.getSlave2Port());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      comnet.minihadoop.common.message.slave.UploadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (comnet.minihadoop.common.message.slave.UploadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientHostname_ = "";
    /**
     * <code>string clientHostname = 1;</code>
     * @return The clientHostname.
     */
    public java.lang.String getClientHostname() {
      java.lang.Object ref = clientHostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientHostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientHostname = 1;</code>
     * @return The bytes for clientHostname.
     */
    public com.google.protobuf.ByteString
        getClientHostnameBytes() {
      java.lang.Object ref = clientHostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientHostname = 1;</code>
     * @param value The clientHostname to set.
     * @return This builder for chaining.
     */
    public Builder setClientHostname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientHostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientHostname = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientHostname() {
      
      clientHostname_ = getDefaultInstance().getClientHostname();
      onChanged();
      return this;
    }
    /**
     * <code>string clientHostname = 1;</code>
     * @param value The bytes for clientHostname to set.
     * @return This builder for chaining.
     */
    public Builder setClientHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientHostname_ = value;
      onChanged();
      return this;
    }

    private int clientPort_ ;
    /**
     * <code>int32 clientPort = 2;</code>
     * @return The clientPort.
     */
    public int getClientPort() {
      return clientPort_;
    }
    /**
     * <code>int32 clientPort = 2;</code>
     * @param value The clientPort to set.
     * @return This builder for chaining.
     */
    public Builder setClientPort(int value) {
      
      clientPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clientPort = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientPort() {
      
      clientPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <code>string filename = 3;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <code>string filename = 3;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userID_ = "";
    /**
     * <code>string userID = 4;</code>
     * @return The userID.
     */
    public java.lang.String getUserID() {
      java.lang.Object ref = userID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userID = 4;</code>
     * @return The bytes for userID.
     */
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      java.lang.Object ref = userID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userID = 4;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userID = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      
      userID_ = getDefaultInstance().getUserID();
      onChanged();
      return this;
    }
    /**
     * <code>string userID = 4;</code>
     * @param value The bytes for userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userID_ = value;
      onChanged();
      return this;
    }

    private boolean initial_ ;
    /**
     * <code>bool initial = 5;</code>
     * @return The initial.
     */
    public boolean getInitial() {
      return initial_;
    }
    /**
     * <code>bool initial = 5;</code>
     * @param value The initial to set.
     * @return This builder for chaining.
     */
    public Builder setInitial(boolean value) {
      
      initial_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool initial = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitial() {
      
      initial_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object slave1Hostname_ = "";
    /**
     * <code>string slave1Hostname = 6;</code>
     * @return The slave1Hostname.
     */
    public java.lang.String getSlave1Hostname() {
      java.lang.Object ref = slave1Hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slave1Hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slave1Hostname = 6;</code>
     * @return The bytes for slave1Hostname.
     */
    public com.google.protobuf.ByteString
        getSlave1HostnameBytes() {
      java.lang.Object ref = slave1Hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slave1Hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slave1Hostname = 6;</code>
     * @param value The slave1Hostname to set.
     * @return This builder for chaining.
     */
    public Builder setSlave1Hostname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      slave1Hostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string slave1Hostname = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlave1Hostname() {
      
      slave1Hostname_ = getDefaultInstance().getSlave1Hostname();
      onChanged();
      return this;
    }
    /**
     * <code>string slave1Hostname = 6;</code>
     * @param value The bytes for slave1Hostname to set.
     * @return This builder for chaining.
     */
    public Builder setSlave1HostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      slave1Hostname_ = value;
      onChanged();
      return this;
    }

    private int slave1Port_ ;
    /**
     * <code>int32 slave1Port = 7;</code>
     * @return The slave1Port.
     */
    public int getSlave1Port() {
      return slave1Port_;
    }
    /**
     * <code>int32 slave1Port = 7;</code>
     * @param value The slave1Port to set.
     * @return This builder for chaining.
     */
    public Builder setSlave1Port(int value) {
      
      slave1Port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 slave1Port = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlave1Port() {
      
      slave1Port_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object slave2Hostname_ = "";
    /**
     * <code>string slave2Hostname = 8;</code>
     * @return The slave2Hostname.
     */
    public java.lang.String getSlave2Hostname() {
      java.lang.Object ref = slave2Hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slave2Hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slave2Hostname = 8;</code>
     * @return The bytes for slave2Hostname.
     */
    public com.google.protobuf.ByteString
        getSlave2HostnameBytes() {
      java.lang.Object ref = slave2Hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slave2Hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slave2Hostname = 8;</code>
     * @param value The slave2Hostname to set.
     * @return This builder for chaining.
     */
    public Builder setSlave2Hostname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      slave2Hostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string slave2Hostname = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlave2Hostname() {
      
      slave2Hostname_ = getDefaultInstance().getSlave2Hostname();
      onChanged();
      return this;
    }
    /**
     * <code>string slave2Hostname = 8;</code>
     * @param value The bytes for slave2Hostname to set.
     * @return This builder for chaining.
     */
    public Builder setSlave2HostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      slave2Hostname_ = value;
      onChanged();
      return this;
    }

    private int slave2Port_ ;
    /**
     * <code>int32 slave2Port = 9;</code>
     * @return The slave2Port.
     */
    public int getSlave2Port() {
      return slave2Port_;
    }
    /**
     * <code>int32 slave2Port = 9;</code>
     * @param value The slave2Port to set.
     * @return This builder for chaining.
     */
    public Builder setSlave2Port(int value) {
      
      slave2Port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 slave2Port = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlave2Port() {
      
      slave2Port_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slave.UploadRequest)
  }

  // @@protoc_insertion_point(class_scope:slave.UploadRequest)
  private static final comnet.minihadoop.common.message.slave.UploadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new comnet.minihadoop.common.message.slave.UploadRequest();
  }

  public static comnet.minihadoop.common.message.slave.UploadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadRequest>() {
    @java.lang.Override
    public UploadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public comnet.minihadoop.common.message.slave.UploadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

